//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eraser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eraser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string btnAdvancedSettings {
            get {
                return ResourceManager.GetString("btnAdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change DNS.
        /// </summary>
        public static string btnChangeDNS {
            get {
                return ResourceManager.GetString("btnChangeDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get DNS List.
        /// </summary>
        public static string btnGetDNSList {
            get {
                return ResourceManager.GetString("btnGetDNSList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter.
        /// </summary>
        public static string lblAdapter {
            get {
                return ResourceManager.GetString("lblAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate DNS.
        /// </summary>
        public static string lblAlternateDNS {
            get {
                return ResourceManager.GetString("lblAlternateDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Host.
        /// </summary>
        public static string lblConfigurationHost {
            get {
                return ResourceManager.GetString("lblConfigurationHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Server.
        /// </summary>
        public static string lblDNSServer {
            get {
                return ResourceManager.GetString("lblDNSServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred DNS.
        /// </summary>
        public static string lblPreferredDNS {
            get {
                return ResourceManager.GetString("lblPreferredDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser - Advanced Settings.
        /// </summary>
        public static string titleAdvancedSettings {
            get {
                return ResourceManager.GetString("titleAdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser.
        /// </summary>
        public static string titleMain {
            get {
                return ResourceManager.GetString("titleMain", resourceCulture);
            }
        }
    }
}
